spring:
  application:
    name: SpringDemo
  data:
    mongodb:
      uri: mongodb+srv://adisawant0178:pJFThshEuiTYp0xj@democluster1.anpte0o.mongodb.net/?retryWrites=true&w=majority&appName=DEMOCluster1
      database: journaldb
      auto-index-creation: true
  profiles:
    active: dev

#logging:
#  level:
#    com:
#      ryzen:
#        journal: ERROR

#for @value purpose
app:
  user:
    name: aditya
    city: pune